[SHARD]
; 是否是 master 服务器，只能存在一个 true，其他全是 false
is_master = true

[STEAM]
; Steam 用的端口，确保每个实例都不相同
authentication_port = 8766
; Steam 用的端口，确保每个实例都不相同
master_server_port = 27016

[NETWORK]
; 监听的 UDP 端口，只能介于 10998 - 11018 之间，确保每个实例都不相同
server_port = 10999